[package]
name = "rhinopuffin"
description = "simple symmetric encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
console = "0.15.8"
rand = "0.8.5"
sha2 = "0.10.8"
